var c = document.getElementById("myCanvas");
var ctx = c.getContext("2d");
ctx.font = "30px Verdana";
ctx.textAlign="center";
ctx.textBaseline="middle";
var rectHeight = 100;
var rectWidth = 1000;
var rectX = 0;
var rectY = 0;
ctx.fillText("Portfolio of Lintu",rectX+(rectWidth/2),rectY+(rectHeight/2));